# Jekyll configuration for lab documentation
title: "Microarchitectural Attacks Lab"
description: "Cache-Based Side-Channel Vulnerabilities"
baseurl: "/teaching_side-channels" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima

# Kramdown settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
  
# Collections
collections:
  exercises:
    output: true

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Include/Exclude
include:
  - code.zip

exclude:
  - Gemfile
  - Gemfile.lock
  - jekyll.sh

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-feed

# Site settings
show_solutions: False
exercise_4_1: False
